### PR TITLE
Dockerfile.base-spack: upgrade from Rocky Linux 8.8 to 8.9

### PR DESCRIPTION
**Pull request by harshula**
* Gadi has been upgraded to Rocky Linux 8.9.

### CODE REVIEW

**Review by CodeGat — APPROVED** [review]
Looks good to me. What are the differences between `8.8` and `8.9`? Do you anticipate any problems with `spack`?

**Comment by aidanheerdegen** [comment]
This will lead to a rebuild of all the CI spack infrastructure I suppose?

**Comment by harshula** [comment]
> Do you anticipate any problems with `spack`?

Building Spack based access-om2 on Gadi succeeded. The Docker dev image build is in-progress.

**Review by aidanheerdegen — APPROVED** [review]

**Comment by harshula** [comment]
Hi @CodeGat, The Docker dev image build succeed.

**Comment by CodeGat** [comment]
🫡 great to hear

**Pull request merged**
